### ISSUE TITLE
数据库脚本初始化失败

### ISSUE THREAD

**Issue by meimosor** [ldystudio/next_digital_campus_server#1]
执行`migrate`后，提示：`"Failed to open the referenced table 'iam_user'"`。详细错误信息：
```
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying rest_framework_tracking.0001_initial...Traceback (most recent call last):
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1824, "Failed to open the referenced table 'iam_user'")       

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\my-project\next_digital_campus_server-master\manage.py", line 23, in <module> 
    main()
  File "E:\my-project\next_digital_campus_server-master\manage.py", line 19, in main     
    execute_from_command_line(sys.argv)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\core\management\commands\migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\migrations\executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\migrations\executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\migrations\executor.py", line 249, in apply_migration
    with self.connection.schema_editor(
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\base\schema.py", line 166, in __exit__
    self.execute(sql)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\base\schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "E:\my-project\next_digital_campus_server-master\venv\Lib\site-packages\MySQLdb\connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1824, "Failed to open the referenced table 'iam_user'")
```

**Comment by ldystudio** [comment]
刚在Mysql 8，数据库字符集utf8mb4上运行成功：
```python
# 新建一个数据库，数据库名配置在local_settings.py文件
# 创建迁移
python manage.py makemigrations

# 检测iam目录下是否出现migrations文件夹，如果没有则运行
python manage.py makemigrations iam

# 迁移
python manage.py migrate

# 之后可以创建一个用户
python manage.py createsuperuser
```

**Comment by meimosor** [comment]
> ```python
> # 检测iam目录下是否出现migrations文件夹，如果没有则运行
> python manage.py makemigrations iam
> ```

第二步执行后可以了，感谢

**Comment by meimosor** [comment]
登录成功后，菜单路由加载失败，是因为数据库没有权限吗？
![image](https://github.com/ldystudio/next_digital_campus_server/assets/31975932/3f5b8915-95b5-4fcd-8a66-0202ced30855)
![image](https://github.com/ldystudio/next_digital_campus_server/assets/31975932/cbe5b643-2b95-49b7-836e-0f4a152d3284)

**Comment by ldystudio** [comment]
看看错误状态码，如果是401，说明没有登录，如果是其他，检查地址和端口号是否和浏览器输入的地址一样。另外还需将后端根目录生成的public.pem放到前端根目录用于校验JWT

**Comment by meimosor** [comment]
> 看看错误状态码，如果是401，说明没有登录，如果是其他，检查地址和端口号是否和浏览器输入的地址一样。另外还需将后端根目录生成的public.pem放到前端根目录用于校验JWT

看了控制台报错是跨域问题，换成127.0.0.1可以了。另外，有个前端问题是不是考虑优化下：
1. 管理界面的路由切换时，每次都需要整个页面刷新，体验不是很友好
2. 首页滚动条，在较高分辨率屏幕下，会出现原生滚动条

**Comment by ldystudio** [comment]
第一点是在Next.js的dev模式下，不会对新页面进行预加载，所以会刷新整个页面，再点击之前的页面就不会整个页面刷新了。在build start后的生产环境下不会出现这个问题。
第二点感谢指正，我已提交最新代码。
